services:
  clueless-frontend:
    image: node:21.6
    container_name: clueless-frontend
    restart: always
    networks:
      - webnet
    working_dir: /app
    volumes:
      - ./web/:/app/
    command: ["npm", "run", "dev"]

  clueless-backend:
    image: "${CLUELESS_REGISTRY}/${CLUELESS_NAMESPACE}/clueless-backend:${CLUELESS_TAG}"
    container_name: clueless-backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/server/
    networks:
      - webnet
      - backend
    env_file:
      - ./server/.env
    depends_on:
      - clueless-redis

  clueless-nginx:
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/conf.d/default.conf
