name: clueless

networks:
  webnet:
  backend:

services:
  clueless-frontend:
    image: "${CLUELESS_REGISTRY}/${CLUELESS_NAMESPACE}/clueless-frontend:${CLUELESS_TAG}"
    container_name: clueless-frontend
    restart: always
    networks:
      - webnet

  clueless-backend:
    image: "${CLUELESS_REGISTRY}/${CLUELESS_NAMESPACE}/clueless-backend:${CLUELESS_TAG}"
    container_name: clueless-backend
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/server/
    networks:
      - webnet
      - backend
    env_file:
      - ./server/.env
    depends_on:
      - clueless-redis

  clueless-redis:
    image: redis:7.2
    container_name: clueless-redis
    hostname: redis
    restart: always
    networks:
      - backend
    command: redis-server --loglevel warning
    expose:
      - 6379

  clueless-nginx:
    image: nginx:1.24
    container_name: clueless-nginx
    hostname: nginx
    restart: always
    networks:
      - webnet
    depends_on:
      - clueless-frontend
      - clueless-backend
    volumes:
      - ./nginx/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/clueless.cassini.dev.crt:/etc/nginx/conf.d/clueless.cassini.dev.crt
      - ./nginx/clueless.cassini.dev.key:/etc/nginx/conf.d/clueless.cassini.dev.key
    ports:
      - 80:80
      - 443:443
