name: clueless
services:
  web:
    image: web
    container_name: web
    build:
      context: ./web
    ports:
      - '3000:3000'
    networks:
      - webnet
    volumes:
      - ./web/:/app/

  server:
    image: server
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./server
    volumes:
      - ./server/:/usr/src/server/
    networks:
      - webnet
      - backend
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - backend
    command: redis-server --loglevel warning
    expose:
      - 6379

networks:
  webnet:
  backend:
