name: clueless
services:
  web:
    image: web
    container_name: web
    restart: always
    build:
      context: ./web
    networks:
      - webnet
    volumes:
      - ./web/:/app/

  server:
    image: server
    container_name: server
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./server
    volumes:
      - ./server/:/usr/src/server/
    networks:
      - webnet
      - backend
    env_file:
      - ./server/.env
    depends_on:
      - redis

  redis:
    image: redis:7.2
    container_name: redis
    hostname: redis
    restart: always
    networks:
      - backend
    command: redis-server --loglevel warning
    expose:
      - 6379

  nginx:
    image: nginx:1.24
    container_name: nginx
    hostname: nginx
    restart: always
    networks:
      - webnet
    depends_on:
      - web
      - server
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80

networks:
  webnet:
  backend:
