# Generated by Django 5.0.2 on 2024-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ws", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("init", "init"),
                    ("move", "move"),
                    ("suggestion", "suggestion"),
                    ("accusation", "accusation"),
                    ("disprove", "disprove"),
                    ("end_turn", "end_turn"),
                    ("query_game", "query_game"),
                    ("chat", "chat"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="EventType",
        ),
    ]
