name: CI

on:
  # Trigger the workflow every time a push is made to the main branch
  push:
    branches:
      - main
  # Trigger the workflow when a pull request is created targeting the main branch
  pull_request:
    branches:
      - main
  # Allows the workflow to be run manually from the Actions tab on GitHub
  workflow_dispatch:

jobs:
  frontend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Node.js
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: 21.6.1

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Lint frontend
        run: npm run lint

      - name: Format frontend
        run: npm run format-ci

  backend:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Setup Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements

      - name: Lint backend
        run: ruff check

      - name: Format backend
        run: black --check .

      # - name: Test
      #   run: python manage.py test
